### PR TITLE
fix: add openedx.yaml file

### PR DESCRIPTION
**Pull request by adamstankiewicz**

### CODE REVIEW

**Comment by nedbat** [comment]
Aren't we trying to use individuals as owners?

**Comment by nedbat** [comment]
(Ditto for the other repos, naturally)

**Comment by brittneyexline** [comment]
hmm, we didn't know that. we thought it made sense to specify the team alias since people come and go.

**Comment by nasthagiri** [comment]
FWIW, we (Scott and I) are actively working on putting forth a proposal on whether/when the owner should be an individual or a team.  Until then, you may want to choose what's best for your own team - before we standardize.

**Comment by adamstankiewicz** [comment]
We went with the team alias (edx/business-enterprise-team) based on other openedx.yaml files in other repos. If this does get standardized, feel free to let us know and we will update the repos :)

**Comment by nedbat** [comment]
OK, my mistake, I was going by the text of the OEP: https://github.com/edx/open-edx-proposals/commit/b77254a5547d9597080b6a0eb433d825daa02d19

**Pull request merged**
